### ISSUE TITLE
Doesn't work for file names with spaces (and other special characters)

### ISSUE THREAD

**Issue by peterholak** [Falc/FlysystemSftpSymlinkPlugin#1]
Wrapping the file names in `escapeshellarg()` would solve most cases, but that function behaves differently on Windows because it's meant for use with local shells.

A much better way would be replacing the shell calls with the symlink functions from phpseclib (which the Flysystem SFTP adapter uses).

**Comment by Falc** [comment]
@peterholak I was not aware of those `symlink()` and `is_link()` methods in `phpseclib\NET\SFTP` so I have just replaced the shell calls. May I ask you to test the latest changes (dev-master)?

**Comment by peterholak** [comment]
The variable name in `Symlink.php` line 65 is wrong, other than that it works great (I tested files, directories, spaces in names, existing links, return values).

There is however a change in behavior where `symlink()` will now create links to non-existent files instead of failing like it was previously. If you want to preserve the behavior from previous version, you need to also check if the target file exists.

**Comment by Falc** [comment]
I have fixed that fail with the variable name. I will make another change to preserve the behavior and test it myself as soon as I find some spare time. Thank you for your help, Peter. :)

**Comment by Falc** [comment]
@peterholak After doing some testing, I don't see any difference between the old `ln -s` code and the new one that uses `phpseclib\NET\SFTP`. Both _versions_ allow to create links to non-existent files without failing.

Could you show an example of those different behaviors?

**Comment by peterholak** [comment]
I just tested it again and you're right - I think I must have left a space in the filename when testing earlier and switching between the versions. So it does work the same as it did before.

**Comment by Falc** [comment]
This is fixed in v1.2.0. :)
